base_config: continuous_diffusion_jointdelta_staged_quicktrial.yaml

control:
  official:
    config_overrides:
      n_obs_steps: 2
      horizon: 8
      n_action_steps: 2
      drop_n_last_frames: 5
      pretrained_backbone_weights: ResNet18_Weights.IMAGENET1K_V1
      use_group_norm: false
      num_inference_steps: 10
