base_config: continuous_act_jointtarget_staged_visualdr_mix_finetune.yaml

control:
  official:
    config_overrides:
      optimizer_lr: 3.0e-6
      optimizer_lr_backbone: 0.0

official_train:
  output_dir: outputs/train/lerobot/act_jointtarget_staged_visualdr_mix_head_finetune
  job_name: roarm_act_jointtarget_staged_visualdr_mix_head_finetune
