base_config: continuous_act_jointtarget_staged_dr_finetune.yaml

data_continuous:
  train_path: data/continuous_jointtarget_staged_dr_mix/train.npz
  val_path: data/continuous_jointtarget_staged_dr_mix/val.npz
  test_path: data/continuous_jointtarget_staged_dr_mix/test.npz

official_train:
  dataset:
    repo_id: roarm_continuous_train_jointtarget_staged_dr_mix
    root: data/lerobot/roarm_continuous_train_jointtarget_staged_dr_mix
  output_dir: outputs/train/lerobot/act_jointtarget_staged_dr_mix_finetune
  job_name: roarm_act_jointtarget_staged_dr_mix_finetune
