base_config: continuous_act_jointtarget_staged_trial.yaml

data_continuous:
  train_path: data/continuous_jointtarget_staged_quicktrial/train.npz
  val_path: data/continuous_jointtarget_staged_quicktrial/val.npz
  test_path: data/continuous_jointtarget_staged_quicktrial/test.npz

official_train:
  dataset:
    repo_id: roarm_continuous_train_jointtarget_staged_quicktrial
    root: data/lerobot/roarm_continuous_train_jointtarget_staged_quicktrial
  output_dir: outputs/train/lerobot/act_jointtarget_staged_quicktrial
  job_name: roarm_act_jointtarget_staged_quicktrial
