base_config: continuous_act_l3only_tiny_jointtarget.yaml

data_continuous:
  train_path: data/continuous_l3only_jointtarget_tiny_vissearch/train.npz
  val_path: data/continuous_l3only_jointtarget_tiny_vissearch/train.npz
  test_path: data/continuous_l3only_jointtarget_tiny_vissearch/train.npz

official_train:
  dataset:
    repo_id: roarm_continuous_train_v2_l3only_jointtarget_tiny_vissearch
    root: data/lerobot/roarm_continuous_train_v2_l3only_jointtarget_tiny_vissearch
  output_dir: outputs/train/lerobot/act_v2_l3only_tiny_jointtarget_vissearch
  job_name: roarm_act_v2_l3only_tiny_jointtarget_vissearch
